chore: release 0.1.0
adfinis-sygroup/ebau-gwr pull request #14
Opened 2021-02-17 10:39 UTC by czosel

2021-02-17 10:46 UTC, open-dynaMIX requested changes
Please also update the Changelog.

2021-02-17 11:20 UTC, czosel commented
Totally. Shall we add semantic-release like in caluma?

2021-02-18 06:34 UTC, open-dynaMIX commented
In Caluma it's just in the dev requirements, in order to help generating Changelogs, right? I'd do the same here.

IMO this release could also just have `initial release` as Changelog.

2021-02-22 09:56 UTC, open-dynaMIX approved these changes

2021-02-22 09:57 UTC, merged