qc login
adfinis-sygroup/ebau-gwr pull request #80
Opened 2022-07-04 17:24 UTC by velrest

- fix(docker): run server with poetry so deps are found
- feat(hous_stat_creds): creds are identified by user and x-camac-group

2022-07-05 18:15 UTC, winged requested changes
Naming functions: use pep8 naming (snake case), otherwise LGTM

2022-07-05 18:15 UTC, winged commented on ebau_gwr/token_proxy/migrations/0003_housingstatcreds_group.py
> +def deleteCredentials(apps, schema_editor):
pep8

2022-07-06 12:49 UTC, velrest commented on ebau_gwr/token_proxy/migrations/0003_housingstatcreds_group.py
> +def deleteCredentials(apps, schema_editor):
My bad, renamed to snake case

2022-07-18 11:53 UTC, fugal-dy commented
looking good!

2022-07-18 11:55 UTC, merged

2022-07-18 11:55 UTC, fugal-dy approved these changes